import 'package:diskit/Models/diskit_chat_card.dart';

List<ChatModel> diskitChat = [
  ChatModel(
    id: 1,
    title: "Quick and easy custom thumbnail",
    image: "assets/images/profile.jpg",
    online: 12,
    likes: 28841,
    noOfUsers: 331,
    unReadChat: 4,
  ),
  ChatModel(
    id: 1,
    title: "Use the Right Keywords for YouTube Search",
    image: "assets/images/profile.jpg",
    online: 12,
    likes: 2815,
    noOfUsers: 331,
    unReadChat: 4,
  ),
  ChatModel(
    id: 1,
    title: "Avoid YouTube Clickbait Titles",
    image: "assets/images/profile.jpg",
    online: 12,
    likes: 8,
    noOfUsers: 331,
    unReadChat: 4,
  ),
  ChatModel(
    id: 1,
    title: "Stay Under the YouTube Title Character Limit",
    image: "assets/images/profile.jpg",
    online: 2,
    likes: 158,
    noOfUsers: 331,
    unReadChat: 4,
  ),
  ChatModel(
    id: 1,
    title: "Quick and easy custom thumbnail",
    image: "assets/images/profile.jpg",
    online: 2,
    likes: 8148,
    noOfUsers: 331,
    unReadChat: 4,
  ),
  ChatModel(
    id: 1,
    title: "9 Ways to Write Exciting YouTube Titles for Your Videos",
    image: "assets/images/profile.jpg",
    online: 2,
    likes: 2458,
    noOfUsers: 331,
    unReadChat: 4,
    // isTap: false,
  ),
  ChatModel(
    id: 1,
    title: " Use Words Your Audience Can Relate To",
    image: null,
    online: 2,
    likes: 3258,
    noOfUsers: 331,
    unReadChat: 4,
  ),
];
